var song_list = {
    "01": {
        title: "Latest Trends Remix",
        artist: "A1 x J1",
        genre: "RAP / DRILL UK",
        duration: "3:09",
        track: "A1 x J1 - Latest Trends Remix ft Aitch.mp3",
    },
    "02": {
        title: "DCB",
        artist: "Guy2Bezbar",
        genre: "RAP / FR",
        duration: "2:58",
        track: "Guy2Bezbar - DCB.mp3",
    },
    "03": {
        title: "TPM",
        artist: "Guy2Bezbar feat Freeze Corleone",
        genre: "RAP / FR",
        duration: "3:11",
        track: "Guy2Bezbar - TPM feat Freeze Corleone.mp3",
    },
    "04": {
        title: "Mona Lisa",
        artist: "Booba feat JSX",
        genre: "RAP / DRILL FR",
        duration: "3:06",
        track: "Booba - Mona Lisa feat JSX.mp3",
    },
    "05": {
        title: "6 For 6",
        artist: "Central Cee",
        genre: "RAP / DRILL UK",
        duration: "2:37",
        track: "Central Cee - 6 For 6 .mp3",
    },
    "06": {
        title: "Moneygram",
        artist: "Nahir feat Freeze Corleone",
        genre: "RAP / DRILL FR",
        duration: "3:20",
        track: "Nahir - Moneygram feat Freeze Corleone.mp3",
    },
    "07": {
        title: "Flicky",
        artist: "Abra Cadabra",
        genre: "RAP / DRILL UK",
        duration: "3:04",
        track: "Abra Cadabra - Flicky.mp3",
    },
    "08": {
        title: "Checkmate",
        artist: "30SET",
        genre: "RAP / DRILL NZ",
        duration: "3:47",
        track: "30SET - Checkmate.mp3",
    },
    "09": {
        title: "Imposters",
        artist: "Jonh Doe",
        genre: "RAP / DRILL UK",
        duration: "2:38",
        track: "Imposters.mp3",
    },
}